# Generated by Django 4.1.5 on 2023-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_active_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='number_of_users',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tag_on_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
