# Generated by Django 4.1.5 on 2023-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptionplan_max_active_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='File', max_length=200),
        ),
    ]
