# Generated by Django 4.1.5 on 2023-04-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinfo_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='subscription',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users_subscribed', to='users.subscriptionplan', to_field='level'),
        ),
    ]
