# Generated by Django 4.1.5 on 2023-04-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userinfo_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(default='profile_pictures/avatar.png', upload_to='profile_pictures/'),
        ),
    ]
