# Generated by Django 4.1.5 on 2023-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userinfo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, upload_to='project_pictures/'),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
