# Generated by Django 4.1.5 on 2023-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectinvite',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
