# Generated by Django 4.1.5 on 2023-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_track_alter_notification_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(default='tracks/track.png', upload_to='tracks/'),
        ),
    ]
