# Generated by Django 4.1.5 on 2023-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_track_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvite',
            name='offered_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
