# Generated by Django 4.1.5 on 2023-04-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_projectinvite_offered_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='profile_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tag_on_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
