# Generated by Django 4.1.5 on 2023-04-30 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_track_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriend',
            name='date_accepted',
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='friend',
        ),
        migrations.AddField(
            model_name='userfriend',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, default='tracks/vinyl-disc.png', upload_to='tracks/'),
        ),
    ]
