# Generated by Django 4.1.5 on 2023-05-01 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_userfriend_date_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='favorite_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
    ]
