# Generated by Django 4.1.5 on 2023-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_task_payout_alter_userrating_target_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
