# Generated by Django 4.1.5 on 2023-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userinfo_date_of_birth_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
