# Generated by Django 4.1.5 on 2023-05-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_access_token',
            new_name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id_token',
        ),
    ]
