# Generated by Django 4.1.5 on 2023-04-14 23:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodyse', '0003_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='favorite_artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='favorite_songs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
