# Generated by Django 4.1.5 on 2023-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodyse', '0009_alter_chat_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
